version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hmcts-backend-app
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cases
      - DB_USER_NAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - hmcts-network

  db:
    image: postgres:15-alpine
    container_name: hmcts-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cases
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hmcts-network

networks:
  hmcts-network:
    driver: bridge

volumes:
  postgres_data:
